version: '3'

services:
  ui:
    build:
      context: ./ui/
    volumes:
      - ui:/var/www/ui
    restart: "no"

  wordpress:
    image: library/wordpress:5.7-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data/wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - backend  #for dev purpose we use a bridged network
    logging:
      driver: journald

  mongo:
    image: mongo:4.2.2-bionic
    container_name: mongo
    restart: unless-stopped
    hostname: mongo
    environment:
      - MONGO_DATA=/data/db
    env_file:
      - env
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/init/:/docker-entrypoint-initdb.d
      - ./log/mongo:/srv/logs
    stop_grace_period: 5m
    networks:
      - frontend
      - backend
    ports:
      - 28017:27017

  postgres:
    build:
      context: ./postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - frontend
      - backend
    ports:
      - 5433:5432
    env_file:
      - env
    restart: unless-stopped
    logging:
      driver: journald

  tasai:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - postgres
      - mongo
    logging:
      driver: journald

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/wordpress_dev.conf:/etc/nginx/conf.d/wordpress.conf:ro
      - ./nginx/tasai_dev.conf:/etc/nginx/conf.d/tasai.conf:ro
      - ./nginx/ui.conf:/etc/nginx/conf.d/ui.conf:ro
      - ./data/wordpress:/var/www/html:ro
      - ./wp-content:/var/www/html/wp-content:ro
      - ui:/var/www/ui:ro
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend
    ports:
      - 8070:80
    logging:
      driver: journald

  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend #for dev purpose we use a bridged network
    logging:
      driver: journald

networks:
  frontend:
    driver: bridge
  backend:

volumes:
  ui:
