version: '3'

services:
  ui:
    build:
      context: ./ui/
    volumes:
      - ui:/var/www/ui
    env_file:
      - ui/.env.preprod
    restart: "no"

  wordpress:
    image: library/wordpress:5.7-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data/wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - backend  #for dev purpose we use a bridged network
    logging:
      driver: journald

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/wordpress_preprod.conf:/etc/nginx/conf.d/wordpress.conf:ro
      - ./nginx/ui_preprod.conf:/etc/nginx/conf.d/ui.conf:ro
      - ./data/wordpress:/var/www/html:ro
      - ./wp-content:/var/www/html/wp-content:ro
      - ui:/var/www/ui:ro
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend
    ports:
      - 8005:80
    env_file:
      - ui/.env.preprod
    logging:
      driver: journald

  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend #for dev purpose we use a bridged network
    logging:
      driver: journald

networks:
  frontend:
    driver: bridge
  backend:

volumes:
  ui:
