export const INDICATOR = 'Indicator';
export const SUB_INDICATOR = 'SubIndicator';
export const EVEN = 'even';
export const ODD = 'odd';
export const LEGEND = 'legend';
export const DISPLAY_TYPE_RATING = 'Rating';
export const DISPLAY_TYPE_NUMBER = 'Number';
export const DISPLAY_TYPE_HHI = 'HHI value (color)';
export const DISPLAY_TYPE_PERCENTAGE = 'Percentage';